development: &development
  adapter: mysql
  database: js_dom_fixtures_development
  username: root
  password: password
  host: localhost
  socket: /tmp/mysql.sock
  
test:
  <<: *development
  database: js_dom_fixtures_test
