---
defaults:
  install_options: --source=http://gems.rubyforge.org --source=http://gems.github.com --source=http://gems.engineyard.com --source=http://gems.pivotallabs.com
gems:
- name: rake
  version: >= 0.8.4
  # check_for_upgrade: true # uncomment this to force an upgrade
- name: rails
  <% if ENV['RAILS_GEM_VERSION'] %>
  # To see more recent preview gems, run 'gem list rails --source=http://gems.rubyonrails.org --remote'
  # To see which of these correspond to a tag, run 'svn log http://svn.rubyonrails.org/rails/tags'
  version: <%= ENV['RAILS_GEM_VERSION'] %>
  <% else %>
  # NOTE: this version should be kept in sync with the default socialitis/pivotal_core Rails version in geminstaller_rails.yml
  version: 2.3.4
  <% end %>
- name: rspec
  version: 1.2.8
- name: rspec-rails
  version: 1.2.7.1
- name: webrat
  version: 0.5.3
- name: thoughtbot-factory_girl
  version: 1.2.2
